# SPDX-FileCopyrightText: 2026 Felix Oertel
# SPDX-License-Identifier: AGPL-3.0-or-later

version = 1

[[annotations]]
path = ["**/*.php", "**/*.js", "**/*.css", "**/*.xml", "**/*.json", "**/*.md"]
SPDX-FileCopyrightText = "2026 Felix Oertel"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ["img/**"]
SPDX-FileCopyrightText = "2026 Felix Oertel"
SPDX-License-Identifier = "AGPL-3.0-or-later"
